# Generated by Django 5.2 on 2025-09-26 13:44

from django.db import migrations, models


def convert_normal_to_anulada(apps, schema_editor):
    Novedad = apps.get_model('novedades', 'Novedad')
    Novedad.objects.filter(estado='normal').update(estado='anulada')


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_normal_to_anulada, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('tardanza', 'Tardanza'), ('ausente', 'Ausente'), ('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad'), ('horario', 'Horario'), ('anulada', 'Anulada')], max_length=20),
        ),
    ]
