# Generated by Django 5.2 on 2025-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_novedad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('tardanza', 'Tardanza'), ('ausente', 'Ausente'), ('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad'), ('horario', 'Horario'), ('anulada', 'Anulada')], default='normal', max_length=20),
        ),
    ]
